version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: myapp
        MYSQL_USER: myapp
        MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
  backend:
    build: ./project_backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/project_backend/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
        DB_USER: root
        DB_PASSWORD: 1234
        DB_NAME: myapp
        DB_HOST: db
